#!/usr/bin/env bash

set -e

PERSONAL=~/personal
BIN=~/bin

DOTFILES_DIRECTORY="${HOME}/.dotfiles"
DOTFILES_TARBALL_PATH="https://github.com/Nerconer/dotfiles/tarball/master"
DOTFILES_GIT_REMOTE="git@github.com:Nerconer/dotfiles.git"

declare -a LINKS="("git" "nano" "nvim" "tmux" "scripts" "zsh")"

echo ""

# If missing, download and extract the dotfiles repository
if [[ ! -d ${DOTFILES_DIRECTORY} ]]; then
	echo "Downloading dotfiles from repository..."
	mkdir "${DOTFILES_DIRECTORY}"
	# Get the tarball
	curl -fsSLo "${HOME}"/dotfiles.tar.gz ${DOTFILES_TARBALL_PATH}
	# Extract to the dotfiles directory
	tar -zxf "${HOME}"/dotfiles.tar.gz --strip-components 1 -C "${DOTFILES_DIRECTORY}"
	# Remove the tarball
	rm -rf "${HOME}"/dotfiles.tar.gz
fi

cd "${DOTFILES_DIRECTORY}"

source ./lib/utils

if ! command_exists 'brew'; then
	setup_homebrew
fi

if ! command_exists 'git'; then
	echo "Updating Homebrew..."	
  brew update
	echo "Installing Git..."
	brew install git
fi

# Initialize the git repository if it's missing
if ! is_git_repo; then
	echo "Initializing git repository..."
	git init
	git remote add origin ${DOTFILES_GIT_REMOTE}
	git fetch origin master
	# Reset the index and working tree to the fetched HEAD
	# (submodules are cloned in the subsequent sync step)
	git reset --hard FETCH_HEAD
	# Remove any untracked files
	git clean -fd
fi

echo -e "Syncing dotfiles..."
# Pull latest changes
git pull --rebase origin master

function usage() {
cat <<EOT
	dotfiles - David Solà
	Usage: $(basename "$0") [options]
	Options:
			-h, --help	Print this help text
			backup     	Generates a Backup file
			link   			Configures all symlinks
			git       	Configures Git
			homebrew    Install dependencies
			shell       Configures Shell
			all       	Full setup and configuration
	Documentation can be found at https://github.com/Nerconer/dotfiles
	Copyright (c) David Solà
	Licensed under the MIT license.
EOT
}

function setup_backup() {
	BACKUP_DIR=$HOME/dotfiles-backup

	title "Creating backup directory at $BACKUP_DIR"
	
	mkdir -p "$BACKUP_DIR"

	for file in "$HOME/.config/nvim" "$HOME/.vim" "$HOME/.vimrc"; do
	    if [ ! -L "$file" ]; then
            echo "Backing up $file"
            cp -rf "$file" "$BACKUP_DIR"
        else
            warning "$file does not exist at this location or is a symlink"
        fi
    done
}

function setup_symlinks() {
	title "Setting up symbolic links"

  for folder in "${LINKS[@]}"; do
    stow -D "$folder"
    stow "$folder"
  done

	if [ -e "$HOME/.local/share/nvim/site/autoload/plug.vim" ]; then
		echo "vim-plug already exists... Skipping"
  else
		echo "Installing vim-plug"
		curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    echo "Installing nvim plugins..."
    nvim --headless +PlugInstall +qall
  fi
}

function setup_git() {
	title "Setting up Git"

	defaultName=$(git config user.name)
	defaultEmail=$(git config user.email)

  read -rp "Name [$defaultName] " name
  read -rp "Email [$defaultEmail] " email

	git config -f ~/.gitconfig-local user.name "${name:-$defaultName}"
  git config -f ~/.gitconfig-local user.email "${email:-$defaultEmail}"
}

function setup_homebrew() {
	title "Setting up Homebrew"
	
	if test ! "$(command -v brew)"; then
		echo "Homebrew not installed. Installing..."
		# Run as a login shell (non-interactive) so that the script doesn't pause for user input
		curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh | bash --login
  fi
	
	# install brew dependencies from Brewfile
  brew bundle
}

function setup_shell() {
	title "Configurating Shell"

	echo "Installing Oh My Zsh..."
	if [ -n "$ZSH" ]; then
		echo "Oh My Zsh already exists, skipping..."
	else
		mkdir oh-my-zsh-temp && cd "$_"
		sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
	fi
}

[ ! -d "$PERSONAL" ] && echo "Creating personal directory..." && mkdir -p "$PERSONAL"

[ ! -d "$BIN" ] && echo "Creating ~/bin directory..." && mkdir "$BIN"

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
	usage
	exit
fi

case "$1" in
	backup)
		setup_backup
		;;
	link)
		setup_symlinks
		;;
	git)
		setup_git
		;;
	homebrew)
		setup_homebrew
		;;
	shell)
		setup_shell
		;;
	all|*)
		setup_symlinks
		setup_shell
		setup_homebrew
		;;
esac

success "Done."
exit 0
